# Generated by Django 3.1.3 on 2021-05-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_Apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bloodgroup',
        ),
    ]
