# Generated by Django 3.1.3 on 2021-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_Apps', '0002_auto_20210508_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bloodgroup',
        ),
    ]
