# Generated by Django 3.1.7 on 2021-03-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_Apps', '0002_delete_receptionist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
