# Generated by Django 3.1.3 on 2021-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Apps', '0004_auto_20210509_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='followupdate',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
